config/routes.rb
Rails.application.routes.draw do
  resources :cats, :only => [:index, :new, :create, :show, :edit, :update]
  resources :cat_rental_requests, :only => [:index, :new, :create, :show]
  resources :cat_rental_requests do
    member do
      post 'approve'
      post 'deny'
    end
  end
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date
#  color       :string
#  name        :string
#  sex         :string(1)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Cat < ActiveRecord::Base

  COLORS = %w(orange black white grey calico)

  has_many :cat_rental_requests, dependent: :destroy

  validates :name, presence: true
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex" }
  validates :color, inclusion: { in: COLORS,
    message: "%{value} is not a valid color" }

  def age
    age = Date.today.year - birth_date.year
    age -= 1 if Date.today < birth_date + age.years #for days before birthday
  end

end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer
#  start_date :date
#  end_date   :date
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ActiveRecord::Base

  STATUSES = %w(PENDING APPROVED DENIED)

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUSES, message: "%{value} is not a valid status" }
  validate  :no_overlapping_approved_requests

  belongs_to :cat

  def overlapping_requests
    params = self.attributes
    results = []

    CatRentalRequest.where(cat_id: cat_id).
    where(<<-SQL, {start_date: start_date, end_date: end_date, id: id})
      id != :id
    AND
    (
        start_date BETWEEN :start_date AND :end_date
      OR
        :start_date BETWEEN start_date AND end_date
    )
    SQL
  end


  def overlapping_approved_requests
    overlapping_requests.where(status: :APPROVED)
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: :PENDING)
  end

  def no_overlapping_approved_requests
    unless overlapping_approved_requests.empty?
      errors[:dates] << "cannot approve two overlapping requests"
    end
  end

  def approve!
    transaction do
      status = "APPROVED"
      self.save
      overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    status = "DENIED"
    self.save
  end

  def pending?
    status == "PENDING"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def create
    @request = CatRentalRequest.new(request_params)
    if @request.save
      redirect_to cats_url
    else
      render(
        text: @request.errors.full_messages,
        status: :unprocessable_entity
      )
    end
  end

  def show
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cats_url
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cats_url
  end

private

  def request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all

    render :index
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      render(
        text: @cat.errors.full_messages,
        status: :unprocessable_entity
      )
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      render :show
    else
      render(
        text: @cat.errors.full_messages,
        status: :unprocessable_entity
      )
    end
  end


  private
 def cat_params
   params.require(:cat).permit(:name, :sex, :birth_date, :color, :description)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Rent a Cat!</h1>
<br>
<form action="/cat_rental_requests" method="POST">
  <label for="cat_id">Pick your cat</label><br>
  <select name="cat_rental_request[cat_id]" id="cat_id">
    <option>    </option>
    <% allcats = Cat.all %>
    <% allcats.each do |cat| %>
      <option value="<%=cat.id%>">
        <%= cat.name %>
      </option>
    <% end %>
  </select>
  <br>
  <label for="start_date">Start date:</label>
  <br>
  <input type="date" name="cat_rental_request[start_date]" id="start_date">
  <br>
  <label for="end_date">End date:</label>
  <br>
  <input type="date" name="cat_rental_request[end_date]" id="end_date">
  <br><br>
  <input type="submit" value="Request rental">
</form>

app/views/cats/_form.html.erb
    <% if @cat.persisted? %>
      <form action ="/cats/<%= @cat.id %>" method="POST">
      <input name="_method" type="hidden" value="PATCH"/>
    <% else %>
      <form action = "/cats" method="POST">
    <% end %>

    <label for="cat_name">Name:</label>
    <br>

    <input name="cat[name]" id="cat_name" type="text" value="<%= @cat.name %>">
    <br><br>
    <input type="radio" name="cat[sex]" id="cat_sex_female" value="F"
    <%= "checked" if @cat.sex == "F" %>>
    <label for="cat_sex_female">lady cat</label>
    <br>
    <input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
    <%= "checked" if @cat.sex == "M" %>>
    <label for="cat_sex_male">gentleman cat</label>
    <br><br>
    <label for="cat_color">Color</label>
    <select name="cat[color]" id="cat_color">
      <option>    </option>
      <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>"
      <%= "selected" if @cat.color == color %>>
        <%= color %>
      </option>
      <% end %>
    </select>
    <br><br>
    <label for="cat_birth_date">Birthdate</label>
    <br>
    <input type="date" name="cat[birth_date]" id="cat_birth_date" value =
    <%= @cat.birth_date %>>
    <br><br>
    <label for="cat_description">Biography</label><br>
    <textarea name="cat[description]" id="cat_description">
      <%= @cat.description %>
    </textarea>

    <br><br>
    <input type="submit"
      <% if @cat.persisted? %>
      value="Update cat"
      <% else %>
      value="Create cat"
      <% end %> >
  </form>

app/views/cats/edit.html.erb
  <h1>Edit <%= @cat.name %></h1>
  <%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<h2>Cats</h2>

<ul>
  <% @cats.each do |cat| %>
    <li><%= cat.name %></li>

  <% end %>
</ul>

app/views/cats/new.html.erb
  <h1>Create a new cat!</h1>
  <%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<h2><%= @cat.name %>'s Stats </h2>

<!-- <table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name  %> </td>
    <td><%= @cat.age   %> </td>
    <td><%= @cat.color %> </td>
    <td><%= @cat.sex   %> </td>
    <td><%= @cat.description  %> </td>
  </tr>
</table> -->

<table>
  <tr>
    <% Cat.attribute_names.each do |data| %>
    <th>
      <%= data %>
    </th>
    <% end %>
  </tr>

  <tr>
    <% Cat.attribute_names.each do |data| %>
    <td>
      <%= @cat.send(data) %>
    </td>
  <% end %>
</tr>
</table>
<br>
<b>Rental Requests</b>
<br>
<% @requests = @cat.cat_rental_requests.order(:start_date) %>
<ul>
<% @requests.each do |request| %>
<li>
ID: <%= request.id %> Start Date: <%= request.start_date %> / End Date: <%= request.end_date %>
<% if request.pending? %>
  <%= button_to "Approve", approve_cat_rental_request_path(request), method: 'POST' %> <%= button_to "Deny", deny_cat_rental_request_path(request), method: "POST" %>
</li>

</ul>
<br>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirCat</title>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>